language: python
python: 
    - "2.7"
    - "3.6"
install:
    - pip install future
    - pip install -r requirements.txt
    - python setup.py -q install
script:
    - python setup.py test
    - python -m test.perf_igor
    - cat test/fixtures/testIgor*/igor.log
    
    
