language: python
python: 
    - "2.7"
    - "3.6"
install:
    - pip install future coverage coveralls
    - pip install -r requirements.txt
    - python setup.py -q install
script:
    - COVERAGE_PROCESS_START=.coveragerc.thread python -m coverage run --rcfile=.coveragerc.thread setup.py test
    - COVERAGE_PROCESS_START=.coveragerc.gevent python -m coverage run --rcfile=.coveragerc.gevent setup.py test
    - python -m test.perf_igor
#    - cat test/fixtures/testIgor*/igor.log
after_success:
    - coverage combine
    - coveralls