language: python
python: 
    - "2.7"
    - "3.6"
install:
    - pip install future coverage coveralls
    - pip install -r requirements.txt
    - python setup.py -q install
script:
    - IGOR_TEST_COVERAGE=True python -m coverage run --parallel-mode --concurrency=greenlet --concurrency=thread --concurrency=gevent setup.py test
    - python -m test.perf_igor
    - cat test/fixtures/testIgor*/igor.log
after_success:
    - coverage combine
    - coveralls