language: python
python: 
    - "2.7"
install:
    - python setup.py -q install
script:
    - python -m unittest discover test
    - python test/perf_igor.py
    - ls -lR test
    - ls -lRL test
    - cat test/fixtures/testIgor/igor.log
    
    
